#ifndef TSVITA_MOONLIGHT_LWIPOPTS_H
#define TSVITA_MOONLIGHT_LWIPOPTS_H

#define NO_SYS 0
#define SYS_LIGHTWEIGHT_PROT 1
#define LWIP_NETCONN 1
#define LWIP_SOCKET 1
#define LWIP_COMPAT_SOCKETS 0
#define LWIP_POSIX_SOCKETS_IO_NAMES 0
#define LWIP_SOCKET_OFFSET 128
#define LWIP_SOCKET_EXTERNAL_HEADERS 1
#define LWIP_SOCKET_HAVE_SA_LEN 1
#define LWIP_SOCKET_EXTERNAL_HEADER_SOCKETS_H "tsvita_socket_external.h"
#define LWIP_SOCKET_EXTERNAL_HEADER_INET_H <arpa/inet.h>
#define LWIP_TIMEVAL_PRIVATE 0
#define LWIP_SOCKET_POLL 1
#define LWIP_NETIF_API 1
#define LWIP_TCPIP_CORE_LOCKING 0
#define LWIP_NETCONN_SEM_PER_THREAD 0

#define LWIP_IPV4 1
#define LWIP_IPV6 0
#define LWIP_ARP 0
#define LWIP_ETHERNET 0
#define LWIP_ICMP 1
#define LWIP_IGMP 0
#define LWIP_RAW 0
#define LWIP_DHCP 0
#define LWIP_AUTOIP 0
#define LWIP_DNS 1
#define LWIP_DNS_API_DECLARE_H_ERRNO 1
#define LWIP_DNS_API_DEFINE_ERRORS 0
#define LWIP_DNS_API_DEFINE_FLAGS 0
#define LWIP_DNS_API_DECLARE_STRUCTS 0

#define LWIP_UDP 1
#define LWIP_TCP 1
#define LWIP_ALTCP 0
#define LWIP_TIMERS 1

#define MEM_ALIGNMENT 4
#define MEM_SIZE (1536U * 1024U)
#define MEM_LIBC_MALLOC 1
#define MEMP_MEM_MALLOC 1

#define MEMP_NUM_NETCONN 64
#define MEMP_NUM_UDP_PCB 24
#define MEMP_NUM_TCP_PCB 24
#define MEMP_NUM_TCP_PCB_LISTEN 4
#define MEMP_NUM_TCP_SEG 256
#define PBUF_POOL_SIZE 256
#define PBUF_POOL_BUFSIZE 1536

#define TCP_MSS 1200
#define TCP_WND (32U * TCP_MSS)
#define TCP_SND_BUF (16U * TCP_MSS)
#define TCP_SND_QUEUELEN 128
#define TCP_QUEUE_OOSEQ 1

#define TCPIP_MBOX_SIZE 128
#define DEFAULT_UDP_RECVMBOX_SIZE 128
#define DEFAULT_TCP_RECVMBOX_SIZE 128
#define DEFAULT_ACCEPTMBOX_SIZE 16
#define TCPIP_THREAD_STACKSIZE (32U * 1024U)
#define TCPIP_THREAD_PRIO 0

#define LWIP_SO_RCVTIMEO 1
#define LWIP_SO_SNDTIMEO 1
#define LWIP_SO_RCVBUF 1
#define SO_REUSE 1
#define LWIP_TCP_KEEPALIVE 1

#define IP_FORWARD 0
#define IP_REASSEMBLY 1
#define IP_REASS_MAX_PBUFS 64
#define MEMP_NUM_REASSDATA 16
#define IP_FRAG 1
#define IP_OPTIONS_ALLOWED 0

#define CHECKSUM_GEN_IP 1
#define CHECKSUM_GEN_UDP 1
#define CHECKSUM_GEN_TCP 1
#define CHECKSUM_CHECK_IP 1
#define CHECKSUM_CHECK_UDP 1
#define CHECKSUM_CHECK_TCP 1
#define LWIP_CHECKSUM_ON_COPY 1

#define LWIP_SINGLE_NETIF 1
#define LWIP_NETIF_STATUS_CALLBACK 0
#define LWIP_NETIF_LINK_CALLBACK 0
#define LWIP_STATS 0
#define LWIP_DEBUG 0
#define LWIP_DONT_PROVIDE_BYTEORDER_FUNCTIONS 1

#endif
