#ifndef TSVITA_LWIPOPTS_H
#define TSVITA_LWIPOPTS_H

#define NO_SYS 1
#define SYS_LIGHTWEIGHT_PROT 0
#define LWIP_NETCONN 0
#define LWIP_SOCKET 0

#define LWIP_IPV4 1
#define LWIP_IPV6 0
#define LWIP_ARP 0
#define LWIP_ETHERNET 0
#define LWIP_ICMP 1
#define LWIP_IGMP 0
#define LWIP_RAW 0
#define LWIP_DHCP 0
#define LWIP_AUTOIP 0
#define LWIP_DNS 0

#define LWIP_UDP 1
#define LWIP_TCP 1
#define LWIP_ALTCP 0

#define NO_SYS_NO_TIMERS 0
#define LWIP_TIMERS 1
#define LWIP_TIMERS_CUSTOM 0

#define MEM_ALIGNMENT 4
#define MEM_SIZE (128U * 1024U)
#define MEM_LIBC_MALLOC 1
#define MEMP_MEM_MALLOC 1

#define MEMP_NUM_UDP_PCB 4
#define MEMP_NUM_TCP_PCB 4
#define MEMP_NUM_TCP_PCB_LISTEN 2
#define MEMP_NUM_TCP_SEG 24
#define PBUF_POOL_SIZE 24
#define PBUF_POOL_BUFSIZE 1536

#define TCP_MSS 1200
#define TCP_WND (4U * TCP_MSS)
#define TCP_SND_BUF (4U * TCP_MSS)
#define TCP_SND_QUEUELEN 16

#define IP_FORWARD 0
#define IP_REASSEMBLY 0
#define IP_FRAG 0
#define IP_OPTIONS_ALLOWED 0

#define CHECKSUM_GEN_IP 1
#define CHECKSUM_GEN_UDP 1
#define CHECKSUM_GEN_TCP 1
#define CHECKSUM_CHECK_IP 1
#define CHECKSUM_CHECK_UDP 1
#define CHECKSUM_CHECK_TCP 1
#define LWIP_CHECKSUM_ON_COPY 1

#define LWIP_SINGLE_NETIF 1
#define LWIP_NETIF_STATUS_CALLBACK 0
#define LWIP_NETIF_LINK_CALLBACK 0
#define LWIP_STATS 0
#define LWIP_DEBUG 0

#endif
